// Auto-generated file. Do not edit manually.
export const migrations = [
  {
    "file": "0000_brave_thunderball.sql",
    "content": "CREATE TABLE `book` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text(500) NOT NULL,\n\t`author` text(300),\n\t`isbn` text(20),\n\t`barcode` text(50),\n\t`price` real,\n\t`language` text(50),\n\t`publisher_id` integer,\n\tFOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nCREATE TABLE `book_gender` (\n\t`book_id` integer NOT NULL,\n\t`gender_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `gender_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`gender_id`) REFERENCES `gender`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE TABLE `gender` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(100) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `gender_name_unique` ON `gender` (`name`);--> statement-breakpoint\nCREATE TABLE `publisher` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(200) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `publisher_name_unique` ON `publisher` (`name`);--> statement-breakpoint\nCREATE TABLE `upload_status` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`filename` text,\n\t`books_count` integer DEFAULT 0,\n\t`processed_count` integer DEFAULT 0,\n\t`error` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n"
  },
  {
    "file": "0001_watery_punisher.sql",
    "content": "CREATE TABLE `book_gender` (\n\t`book_id` integer NOT NULL,\n\t`gender_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `gender_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`gender_id`) REFERENCES `gender`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nPRAGMA foreign_keys=OFF;--> statement-breakpoint\nCREATE TABLE `__new_book` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text(500) NOT NULL,\n\t`author` text(300),\n\t`isbn` text(20),\n\t`barcode` text(50),\n\t`price` real,\n\t`language` text(50),\n\t`publisher_id` integer,\n\tFOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nINSERT INTO `__new_book`(\"id\", \"title\", \"author\", \"isbn\", \"barcode\", \"price\", \"language\", \"publisher_id\") SELECT \"id\", \"title\", \"author\", \"isbn\", \"barcode\", \"price\", \"language\", \"publisher_id\" FROM `book`;--> statement-breakpoint\nDROP TABLE `book`;--> statement-breakpoint\nALTER TABLE `__new_book` RENAME TO `book`;--> statement-breakpoint\nPRAGMA foreign_keys=ON;"
  },
  {
    "file": "0002_complete_magneto.sql",
    "content": "PRAGMA foreign_keys=OFF;\n--> statement-breakpoint\nCREATE TABLE `book_genre` (\n\t`book_id` integer NOT NULL,\n\t`genre_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `genre_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`genre_id`) REFERENCES `genre`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE TABLE `genre` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(100) NOT NULL\n);\n--> statement-breakpoint\nINSERT INTO `genre` (`id`, `name`) SELECT `id`, `name` FROM `gender`;\n--> statement-breakpoint\nINSERT INTO `book_genre` (`book_id`, `genre_id`) SELECT `book_id`, `gender_id` FROM `book_gender`;\n--> statement-breakpoint\nDROP TABLE `book_gender`;\n--> statement-breakpoint\nDROP TABLE `gender`;\n--> statement-breakpoint\nCREATE UNIQUE INDEX `genre_name_unique` ON `genre` (`name`);\n--> statement-breakpoint\nPRAGMA foreign_keys=ON;"
  }
];
