// Auto-generated file. Do not edit manually.
export const migrations = [
  {
    "file": "0000_calm_ma_gnuci.sql",
    "content": "CREATE TABLE `book` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text(500) NOT NULL,\n\t`author` text(300),\n\t`isbn` text(20),\n\t`barcode` text(50),\n\t`price` real,\n\t`language` text(50),\n\t`publisher_id` integer,\n\tFOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `book_isbn_idx` ON `book` (`isbn`);--> statement-breakpoint\nCREATE UNIQUE INDEX `book_unique_idx` ON `book` (`title`,`author`,`isbn`);--> statement-breakpoint\nCREATE TABLE `book_genre` (\n\t`book_id` integer NOT NULL,\n\t`genre_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `genre_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`genre_id`) REFERENCES `genre`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE TABLE `genre` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(100) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `genre_name_unique` ON `genre` (`name`);--> statement-breakpoint\nCREATE TABLE `publisher` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(200) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `publisher_name_unique` ON `publisher` (`name`);--> statement-breakpoint\nCREATE TABLE `upload_status` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`filename` text,\n\t`books_count` integer DEFAULT 0,\n\t`processed_count` integer DEFAULT 0,\n\t`error` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n"
  },
  {
    "file": "0000_true_gladiator.sql",
    "content": "CREATE TABLE `book` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text(500) NOT NULL,\n\t`author` text(300),\n\t`isbn` text(20),\n\t`barcode` text(50),\n\t`price` real,\n\t`language` text(50),\n\t`publisher_id` integer,\n\tFOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nCREATE TABLE `book_genre` (\n\t`book_id` integer NOT NULL,\n\t`genre_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `genre_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`genre_id`) REFERENCES `genre`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE TABLE `genre` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(100) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `genre_name_unique` ON `genre` (`name`);--> statement-breakpoint\nCREATE TABLE `publisher` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(200) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `publisher_name_unique` ON `publisher` (`name`);--> statement-breakpoint\nCREATE TABLE `upload_status` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`filename` text,\n\t`books_count` integer DEFAULT 0,\n\t`processed_count` integer DEFAULT 0,\n\t`error` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n"
  },
  {
    "file": "0000_yielding_magik.sql",
    "content": "CREATE TABLE `book` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`title` text(500) NOT NULL,\n\t`author` text(300),\n\t`isbn` text(20),\n\t`barcode` text(50),\n\t`price` real,\n\t`language` text(50),\n\t`publisher_id` integer,\n\tFOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE no action ON DELETE set null\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `book_isbn_idx` ON `book` (`isbn`);--> statement-breakpoint\nCREATE UNIQUE INDEX `book_unique_idx` ON `book` (`title`,`author`,`isbn`);--> statement-breakpoint\nCREATE TABLE `book_genre` (\n\t`book_id` integer NOT NULL,\n\t`genre_id` integer NOT NULL,\n\tPRIMARY KEY(`book_id`, `genre_id`),\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade,\n\tFOREIGN KEY (`genre_id`) REFERENCES `genre`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE TABLE `genre` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(100) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `genre_name_unique` ON `genre` (`name`);--> statement-breakpoint\nCREATE TABLE `publisher` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`name` text(200) NOT NULL\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `publisher_name_unique` ON `publisher` (`name`);--> statement-breakpoint\nCREATE TABLE `upload_status` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`status` text NOT NULL,\n\t`filename` text,\n\t`books_count` integer DEFAULT 0,\n\t`processed_count` integer DEFAULT 0,\n\t`error` text,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL\n);\n"
  },
  {
    "file": "0001_cute_nocturne.sql",
    "content": "CREATE UNIQUE INDEX `book_isbn_unique` ON `book` (`isbn`);--> statement-breakpoint\nCREATE UNIQUE INDEX `book_dedupe_unique` ON `book` (`title`,`author`,`isbn`);"
  },
  {
    "file": "0002_yellow_lifeguard.sql",
    "content": "DROP INDEX `book_isbn_unique`;--> statement-breakpoint\nDROP INDEX `book_dedupe_unique`;--> statement-breakpoint\nCREATE UNIQUE INDEX `book_isbn_idx` ON `book` (`isbn`);--> statement-breakpoint\nCREATE UNIQUE INDEX `book_unique_idx` ON `book` (`title`,`author`,`isbn`);"
  },
  {
    "file": "0003_superb_expediter.sql",
    "content": "CREATE TABLE `book_stock` (\n\t`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,\n\t`book_id` integer NOT NULL,\n\t`bookshelf` text(100),\n\t`number_of_copies` integer DEFAULT 0 NOT NULL,\n\t`number_of_copies_sold` integer DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`book_id`) REFERENCES `book`(`id`) ON UPDATE no action ON DELETE cascade\n);\n--> statement-breakpoint\nCREATE UNIQUE INDEX `book_stock_book_id_unique` ON `book_stock` (`book_id`);"
  }
];
